# Generated by Django 5.1.2 on 2025-02-09 07:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_buy'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='buy',
            name='price',
        ),
    ]
