# Generated by Django 5.1.5 on 2025-02-11 06:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_invitationcard_invitationcategory_item_itemcategory_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='invitationcategory',
            name='price',
        ),
    ]
