# Generated by Django 5.1.5 on 2025-02-11 06:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_remove_invitationcategory_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='invitationcard',
            name='theme',
        ),
    ]
